CREATE OR REPLACE STREAM customer_stream ON EXTERNAL TABLE CORE_DWH.customer_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM lineitem_stream ON EXTERNAL TABLE CORE_DWH.lineitem_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM nation_stream ON EXTERNAL TABLE CORE_DWH.nation_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM orders_stream ON EXTERNAL TABLE CORE_DWH.order_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM part_stream ON EXTERNAL TABLE CORE_DWH.part_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM partsupp_stream ON EXTERNAL TABLE CORE_DWH.partsupp_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM region_stream ON EXTERNAL TABLE CORE_DWH.region_ext INSERT_ONLY = TRUE;
CREATE OR REPLACE STREAM supplier_stream ON EXTERNAL TABLE CORE_DWH.supplier_ext INSERT_ONLY = TRUE;